from setuptools import setup, find_packages
import os
import site

from ukcp_sf import __version__


def readme():
    with open('README.md') as f:
        return f.read()

GIT_REPO = "https://github.com/ukcp-data/ukcp-data-processor"

setup(
    name                 = "ukcp-spatial-files",
    version              = __version__,
    description          = "Python library for reading UKCP shape files.",
    long_description     = readme(),
    license              = "BSD 2-Clause License",
    author               = "Antony Wilson",
    author_email         = "antony.wilson@stfc.ac.uk",
    url                  = GIT_REPO,
    packages             = find_packages(),
    tests_require        = ['pytest'],
    classifiers          = [
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'License :: BSD 2-Clause License',
        'Operating System :: POSIX :: Linux',
        'Programming Language :: Python',
        'Topic :: Scientific/Engineering',
    ],
    include_package_data = True,
    scripts=[],
    entry_points = {},
    package_data = {},
    data_files = [('spatial-files', [
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km.dbf',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km.geojson',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km.prj',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km.shp',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km.shx',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km-wind.dbf',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km-wind.geojson',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km-wind.prj',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km-wind.shp',
            'spatial-files/ukcp18-uk-land-12km/ukcp18-uk-land-12km-wind.shx',
            'spatial-files/ukcp18-uk-land-25km/ukcp18-uk-land-25km.dbf',
            'spatial-files/ukcp18-uk-land-25km/ukcp18-uk-land-25km.geojson',
            'spatial-files/ukcp18-uk-land-25km/ukcp18-uk-land-25km.prj',
            'spatial-files/ukcp18-uk-land-25km/ukcp18-uk-land-25km.shp',
            'spatial-files/ukcp18-uk-land-25km/ukcp18-uk-land-25km.shx',
            'spatial-files/ukcp18-uk-land-5km/ukcp18-uk-land-5km.dbf',
#             'spatial-files/ukcp18-uk-land-5km/ukcp18-uk-land-5km.geojson',
            'spatial-files/ukcp18-uk-land-5km/ukcp18-uk-land-5km.prj',
            'spatial-files/ukcp18-uk-land-5km/ukcp18-uk-land-5km.shp',
            'spatial-files/ukcp18-uk-land-5km/ukcp18-uk-land-5km.shx',
            'spatial-files/ukcp18-uk-land-60km/ukcp18-uk-land-60km.dbf',
            'spatial-files/ukcp18-uk-land-60km/ukcp18-uk-land-60km.geojson',
            'spatial-files/ukcp18-uk-land-60km/ukcp18-uk-land-60km.prj',
            'spatial-files/ukcp18-uk-land-60km/ukcp18-uk-land-60km.shp',
            'spatial-files/ukcp18-uk-land-60km/ukcp18-uk-land-60km.shx',
            'spatial-files/ukcp18-uk-land-country-hires/ukcp18-uk-land-country-hires.dbf',
            'spatial-files/ukcp18-uk-land-country-hires/ukcp18-uk-land-country-hires.geojson',
            'spatial-files/ukcp18-uk-land-country-hires/ukcp18-uk-land-country-hires.prj',
            'spatial-files/ukcp18-uk-land-country-hires/ukcp18-uk-land-country-hires.shp',
            'spatial-files/ukcp18-uk-land-country-hires/ukcp18-uk-land-country-hires.shx',
            'spatial-files/ukcp18-uk-land-country-lowres/ukcp18-uk-land-country-lowres.dbf',
            'spatial-files/ukcp18-uk-land-country-lowres/ukcp18-uk-land-country-lowres.geojson',
            'spatial-files/ukcp18-uk-land-country-lowres/ukcp18-uk-land-country-lowres.prj',
            'spatial-files/ukcp18-uk-land-country-lowres/ukcp18-uk-land-country-lowres.shp',
            'spatial-files/ukcp18-uk-land-country-lowres/ukcp18-uk-land-country-lowres.shx',
            'spatial-files/ukcp18-uk-land-region-hires/ukcp18-uk-land-region-hires.dbf',
            'spatial-files/ukcp18-uk-land-region-hires/ukcp18-uk-land-region-hires.geojson',
            'spatial-files/ukcp18-uk-land-region-hires/ukcp18-uk-land-region-hires.prj',
            'spatial-files/ukcp18-uk-land-region-hires/ukcp18-uk-land-region-hires.shp',
            'spatial-files/ukcp18-uk-land-region-hires/ukcp18-uk-land-region-hires.shx',
            'spatial-files/ukcp18-uk-land-region-lowres/ukcp18-uk-land-region-lowres.dbf',
            'spatial-files/ukcp18-uk-land-region-lowres/ukcp18-uk-land-region-lowres.geojson',
            'spatial-files/ukcp18-uk-land-region-lowres/ukcp18-uk-land-region-lowres.prj',
            'spatial-files/ukcp18-uk-land-region-lowres/ukcp18-uk-land-region-lowres.shp',
            'spatial-files/ukcp18-uk-land-region-lowres/ukcp18-uk-land-region-lowres.shx',
            'spatial-files/ukcp18-uk-land-river-hires/ukcp18-uk-land-river-hires.dbf',
            'spatial-files/ukcp18-uk-land-river-hires/ukcp18-uk-land-river-hires.geojson',
            'spatial-files/ukcp18-uk-land-river-hires/ukcp18-uk-land-river-hires.prj',
            'spatial-files/ukcp18-uk-land-river-hires/ukcp18-uk-land-river-hires.shp',
            'spatial-files/ukcp18-uk-land-river-hires/ukcp18-uk-land-river-hires.shx',
#             'spatial-files/ukcp18-uk-land-river-lowres/ukcp18-uk-land-river-lowres.dbf',
            'spatial-files/ukcp18-uk-land-river-lowres/ukcp18-uk-land-river-lowres.geojson',
            'spatial-files/ukcp18-uk-land-river-lowres/ukcp18-uk-land-river-lowres.prj',
            'spatial-files/ukcp18-uk-land-river-lowres/ukcp18-uk-land-river-lowres.shp',
            'spatial-files/ukcp18-uk-land-river-lowres/ukcp18-uk-land-river-lowres.shx',
            'spatial-files/ukcp18-uk-marine-coast-gridded/ukcp18-uk-marine-coast-gridded.dbf',
            'spatial-files/ukcp18-uk-marine-coast-gridded/ukcp18-uk-marine-coast-gridded.prj',
            'spatial-files/ukcp18-uk-marine-coast-gridded/ukcp18-uk-marine-coast-gridded.geojson',
            'spatial-files/ukcp18-uk-marine-coast-gridded/ukcp18-uk-marine-coast-gridded.shp',
            'spatial-files/ukcp18-uk-marine-coast-gridded/ukcp18-uk-marine-coast-gridded.shx',
            'spatial-files/ukcp18-uk-marine-coastline-hires/ukcp18-uk-marine-coastline-hires.dbf',
            'spatial-files/ukcp18-uk-marine-coastline-hires/ukcp18-uk-marine-coastline-hires.geojson',
            'spatial-files/ukcp18-uk-marine-coastline-hires/ukcp18-uk-marine-coastline-hires.prj',
            'spatial-files/ukcp18-uk-marine-coastline-hires/ukcp18-uk-marine-coastline-hires.shp',
            'spatial-files/ukcp18-uk-marine-coastline-hires/ukcp18-uk-marine-coastline-hires.shx',
            'spatial-files/ukcp18-uk-marine-coastline-lowres/ukcp18-uk-marine-coastline-lowres.dbf',
#             'spatial-files/ukcp18-uk-marine-coastline-lowres/ukcp18-uk-marine-coastline-lowres.geojson',
            'spatial-files/ukcp18-uk-marine-coastline-lowres/ukcp18-uk-marine-coastline-lowres.prj',
            'spatial-files/ukcp18-uk-marine-coastline-lowres/ukcp18-uk-marine-coastline-lowres.shp',
            'spatial-files/ukcp18-uk-marine-coastline-lowres/ukcp18-uk-marine-coastline-lowres.shx',
            'spatial-files/ukcp18-uk-marine-gauge-gridded/ukcp18-uk-marine-gauge-gridded.prj',
            'spatial-files/ukcp18-uk-marine-gauge-gridded/ukcp18-uk-marine-gauge-gridded.dbf',
            'spatial-files/ukcp18-uk-marine-gauge-gridded/ukcp18-uk-marine-gauge-gridded.geojson',
            'spatial-files/ukcp18-uk-marine-gauge-gridded/ukcp18-uk-marine-gauge-gridded.shp',
            'spatial-files/ukcp18-uk-marine-gauge-gridded/ukcp18-uk-marine-gauge-gridded.shx',
            ])]
)
